name: Metrics

on:
  repository_dispatch:
    types: [test_trigger]
  workflow_dispatch:
  schedule:
    # Runs at 4am JST
    - cron: '30 19 * * *'

jobs:
  github-metrics:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_PROJECTS: "False"
          SHOW_PROFILE_VIEWS: "False"
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_TOKEN }}
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}    # Required
          plugin_wakatime_days: 7                                   # Display last week stats
          plugin_wakatime_sections: time, projects, projects-graphs # Display time and projects sections, along with projects graphs
          plugin_wakatime_limit: 4                                  # Show 4 entries per graph
          plugin_wakatime_url: https://wakatime.com                 # Wakatime url endpoint
          plugin_wakatime_user: .user.login                         # User
          plugin_achievements: yes
          plugin_achievements_threshold: B                          # Display achievements with rank B or higher
          plugin_achievements_secrets: yes                          # Display unlocked secrets achievements
          plugin_achievements_ignored: octonaut                     # Hide octonaut achievement
          plugin_achievements_limit: 0                              # Display all unlocked achievement matching threshold and secrets params
          plugin_topics: yes
          plugin_topics_sort: stars                                 # Sort by most starred topics
          plugin_topics_mode: mastered                              # Display icons instead of labels
          plugin_topics_limit: 0                                    # Disable limitations
      # - uses: avinal/Profile-Readme-WakaTime@master
      #   with:
      #     WAKATIME_API_KEY: ${{ secrets.WAKATIME_TOKEN }}
      #     GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      # - uses: athul/waka-readme@master
      #   with:
      #     WAKATIME_API_KEY: ${{ secrets.WAKATIME_TOKEN }}
