name: Metrics

on:
  repository_dispatch:
    types: [test_trigger]
  workflow_dispatch:
  schedule:
    # Runs at 4am JST
    - cron: '30 19 * * *'

jobs:
  github-metrics:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_TOKEN }}                            # GitHub Personal Token
          plugin_introduction: yes
          plugin_introduction_title: yes                            # Hide section title
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year                    # Display full year instead of half year
          plugin_followup: yes
          plugin_followup_sections: repositories, user              # Display overall status of issues/pull requests created on user's repositories and created by user
          plugin_achievements: yes
          plugin_achievements_threshold: B                          # Display achievements with rank B or higher
          plugin_achievements_secrets: yes                          # Display unlocked secrets achievements
          plugin_achievements_display: compact                      # Use compact display
          plugin_achievements_limit: 0                              # Display all unlocked achievements (no limit)
          plugin_achievements_ignored: octonaut                     # Hide "octonaut" achievement
          plugin_achievements_only: explorer                        # Display only "explorer" achievement (don't use with "ignored" option)
          plugin_topics: yes
          plugin_topics_sort: stars                                 # Sort by most starred topics
          plugin_topics_mode: mastered                              # Display icons instead of labels
          plugin_topics_limit: 0                                    # Disable limitations
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}      # Required
          plugin_wakatime_days: 7                                   # Display last week stats
          plugin_wakatime_sections: time, projects, projects-graphs # Display time and projects sections, along with projects graphs
          plugin_wakatime_limit: 4                                  # Show 4 entries per graph
          plugin_wakatime_url: https://wakatime.com                 # Wakatime url endpoint
          plugin_wakatime_user: .user.login                         # User
